name: assaultcube
version: '1.2.0.2'
summary: Realistic first-person shooter
description: |
  AssaultCube is a first-person shooter set in a realistic-looking environment.
  The arcade-style gameplay is fast-pased and favours team oriented, multiplayer fun.

grade: devel
confinement: devmode

apps:
  assaultcube:
    command: bin/client-launcher.sh
  server:
    command: bin/server-launcher.sh

parts:
  assaultcube:
    plugin: dump
    source: https://github.com/assaultcube/AC/releases/download/v1.2.0.2/AssaultCube_v1.2.0.2.tar.bz2
    organize:
      ./*: bin/
    stage:
      - -bin/source/
      - -bin/*.sh

  client-launcher:
    plugin: dump
    after: [assaultcube]
    source: .
    stage:
      - bin/client-launcher.sh
    organize:
      client-launcher.sh: bin/client-launcher.sh

  server-launcher:
    plugin: dump
    after: [assaultcube]
    source: .
    stage:
      - bin/server-launcher.sh
    organize:
      server-launcher.sh: bin/server-launcher.sh

  libs:
    plugin: nil
    after: [assaultcube]
    stage-packages:
      - libgl1-mesa-dri
      - libsdl1.2debian
      - libsdl-image1.2
      - zlib1g
      - libogg0
      - libvorbis0a
      - libopenal1
