name: assaultcube
version: '1.2.0.2'
summary: Realistic first-person shooter
description: |
  AssaultCube is a first-person shooter set in a realistic-looking environment.
  The arcade-style gameplay is fast-pased and favours team oriented, multiplayer fun.

grade: devel
confinement: devmode

apps:
  assaultcube:
    command: assaultcube.sh

parts:
  assaultcube:
    # TODO: Use a Makefile to drive the build and install
    plugin: make
    source: https://github.com/assaultcube/AC.git
    make-parameters: ["install", "--directory=source/src", "ACDEBUG=yes"]
    artifacts:
      - bin_unix/
      - bot/
      - config/
      - demos/
      - docs/
      - mods/
      - packages/
      - screenshots/
      - scripts/
      - README.html
      - changelog.txt
    build-packages:
      - build-essential
      - clang
      - libsdl1.2debian
      - libsdl1.2-dev
      - libsdl-image1.2
      - libsdl-image1.2-dev
      - libopenal1
      - libopenal-dev
      - libvorbis-dev
      - libcurl3
      - libcurl4-openssl-dev
  client-launcher:
    plugin: dump
    after: [assaultcube]
    source: .
    stage:
      - assaultcube.sh
  libs:
    plugin: nil
    after: [assaultcube]
    stage-packages:
      - libgl1-mesa-dri
      - libsdl1.2debian
      - libsdl-image1.2
      - zlib1g
      - libogg0
      - libvorbis0a
      - libopenal1
