name: assaultcube-alonso
version: '1.2.0.2'
summary: Arcade first-person shooter
description: |
  AssaultCube is a fast-paced and arcade first-person shooter in 3D targeted at
  low spec computers and low latency connections.
  User configuration files are stored in:
    ~/snap/assaultcube-alonso/current/<VERSION>
  General configuration files are stored in:
    /var/snap/assaultcube-alonso/current/<VERSION>

grade: devel
confinement: strict

apps:
  assaultcube-alonso:
    command: bin/client-launcher.sh
    plugs:
      - x11
      - opengl
      - pulseaudio
      - network
  server:
    command: bin/server-launcher.sh
    plugs:
      - network
      - network-bind

parts:
  assaultcube:
    plugin: dump
    source: https://github.com/assaultcube/AC/releases/download/v1.2.0.2/AssaultCube_v1.2.0.2.tar.bz2
    # Temporary solution to avoid warnings in prime step until
    # a better solution comes
    install: |
      ARCH=$(uname -p)
      case $ARCH in
        x86_64)
          rm $SNAPCRAFT_PART_INSTALL/bin_unix/linux_client $SNAPCRAFT_PART_INSTALL/bin_unix/linux_server;;
       *)
          rm $SNAPCRAFT_PART_INSTALL/bin_unix/linux_64_client $SNAPCRAFT_PART_INSTALL/bin_unix/linux_64_server;;
      esac
    organize:
      ./*: bin/
    stage:
      - -bin/source/
      - -bin/*.sh

  client-launcher:
    plugin: dump
    after: [assaultcube]
    source: .
    stage:
      - bin/client-launcher.sh
    organize:
      client-launcher.sh: bin/client-launcher.sh

  server-launcher:
    plugin: dump
    after: [assaultcube]
    source: .
    stage:
      - bin/server-launcher.sh
    organize:
      server-launcher.sh: bin/server-launcher.sh

  libs:
    plugin: nil
    after: [assaultcube]
    build-packages:
      - pulseaudio
    stage-packages:
      - libcurl3
      - libgcc1
      - libgl1-mesa-glx
      - libopenal1
      - libsdl-image1.2
      - libsdl1.2debian
      - libvorbisfile3
      - libx11-6
      - zlib1g

